### PR TITLE
Implemented Search Sort Paginate

### LINKED ISSUE #55: Search Sort Paginate
One of the final things we need for the members page is the feature to search, sort, and paginate the data. I've implemented most of the UI and stuff on the Members page, we just need you to implement the logic that actually does the work. I've described the logic in the `/util/searchSortPaginate.ts` file, but here it is repeated:
```
1. use fuzzy search across all elements of each member
    you can probably do this really easily by concatenating
    the values into a string and then using indexOf
    2. sort the elements that made it through
    3. paginate by putting elements in arrays of length N (array.splice)
    
    return an array of those paginated arrays
```

The reason we're returning an array of arrays is so we can just index them and get the different pages that way instead of having to do all the work to paginate/cache/manage the data from Supabase.

### PR DESCRIPTION
**Pull request by 04AJ**
**What type of PR is this? (check applicable) 🚧**

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

**Describe your PR request 🔥**
Implemented logic to search, sort, and paginate table data. Removed presentable data state obj in member.tsx.

**Mobile & Desktop Screenshots/Recordings 📷**

ssp1
ssp2

**Related Issues 🩹**
Closes #55 

**Added to documentation? 📝**

- [ ] 📜 readme
- [ ] 📜 other
- [x] 🙅 no documentation needed

**Additional context 🗒️**
None

### CODE REVIEW

**Review by seesjays — CHANGES_REQUESTED** [review]
👍 This is some great stuff, love the comparison func. Pagination isn't working though, as you're only adding 1 array of the pagination length to the output.

There should be as many arrays of the pagination length in the output array as possible, and it's ez to get that done. You're gonna want to replace the current code you have for pagination with the following loop:

```tsx
while (newArr.length > 0)
{
    output.push(newArr.splice(0, cfg.paginate);
}
```

**Comment by seesjays** [comment]
That block ^ removes X number of elements from the newArr, makes them into an array, and adds them to the output till there's nothing left. I tested it out a while back but ran into some bugs because I was operating on data directly, but since you make `newArr` you should be good to use it.

**Comment by seesjays** [comment]
Really good stuff otherwise, this is pretty much the last thing we needed for the contacts page 🎉

**Comment by 04AJ** [comment]
Sorry about that, I just pushed the corrected paginate code to the file

**Comment by seesjays** [comment]
Fantastic stuff Alan! 🎉 this helps a ton, tysm

**Review by seesjays — APPROVED** [review]

**Pull request merged**
