### PR TITLE
Made a Loading Spinner

### PR DESCRIPTION
**Pull request by Ashishjob**
I changed it to a relatively simpler one, but two things different are that it doesn't have the word "Loading..." and it might be a bit too high up, so just lmk if I should take care of that.

### CODE REVIEW

**Comment by seesjays** [comment]
Now it doesn't spin! You can just change the SVG to a partial circle so it actually spins, or you can change the animation style to animate-pulse, which I found also looks okay for a loading indicator.
image

**Comment by Ashishjob** [comment]
Oopsies, I didn't realize that I didn't change the partial circle to a different color so it couldn't be easily seen, but I made it a lighter color now so that it actually appears to be spinning.

**Comment by Brodypen** [comment]
This closes #23

**Review by seesjays — APPROVED** [review]
Looks fantastic!

**Pull request merged**
