### PR TITLE
Modular DataTable and Mantine Removal

### LINKED ISSUE #16: ✨ Create data table
Create a modular table that can receive columns and data.

Ideally prep future capability to have a modal popup when clicking on row.

Design:
```jsx
import { Table } from '@mantine/core';

function Demo({columns, data}) {
  return (
    <Table highlightOnHover>
      {/* {...rows} */}
    </Table>
  );
}
```

image

### PR DESCRIPTION
**Pull request by seesjays**
**What type of PR is this? (check applicable) 🚧**

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

**Describe your PR request 🔥**

Adds a wrapper component for HTML table styles, as well as a demo of it.
Also implements the DataTable on the Members page.

**Mobile & Desktop Screenshots/Recordings 📷**

Screen Shot 2023-01-19 at 11 29 25 PM

Screen Shot 2023-01-19 at 11 31 38 PM

Screen Shot 2023-01-19 at 11 53 54 PM

**Related Issues 🩹**

Resolves #16 

**Added to documentation? 📝**

- [ ] 📜 readme
- [ ] 📜 other
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by Junnyyy** [comment]
I didn't specify this clearly, but I believe the approach should be passing the columns and data as props rather than as children. It would better separate the component and alleviate the need to use Tailwind's `@apply`.

An example would be more like this.
```jsx
const data = fetch(...);
const columns = ["Contact ID", "UH ID", ...];

return (
  <Datatable columns={columns} rows={data} />
);
```

**Review by Junnyyy — CHANGES_REQUESTED** [review]
DataTable.tsx
- I would move the interface into the official types file. 
- Would also suggest a type instead of an interface for more clarity
- Demo data?

Types.ts
- Follow the camelCase name structure!

General
- I suggest that you use the Tailwind theme system for the colors you reuse. Through theme: extend. An example of a spot is the layout `bg-[#1C1C1C]` I'd change a custom color.

**Comment by seesjays** [comment]
I made a component demonstrating DataTable usage with some dummy values from the figma file.

79C63DA6-750B-45CD-ACFE-F760FB083D24

**Review by Junnyyy — CHANGES_REQUESTED** [review]
I should've stated the "Demo data?" more clearer. I was meaning for you to remove demo data from the code.

**Review by Junnyyy — APPROVED** [review]
Looks Good! 👍

**Pull request merged**
